import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import StoreProvider from "@/Providers/storeProvider";
import './globals.css';

export const metadata: Metadata = {
  title: "BonVoyage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <ToastContainer position="top-center" />
        <StoreProvider>
          <div className="layout">
            <div className="layout__header">{/* <Header /> */}</div>
            <div className="layout__body">{children}</div>
            <div className="layout__footer">{/* <Footer /> */}</div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
