import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import StoreProvider from "@/Providers/storeProvider";
import './globals.css';
import Navbar from "@/components/molecules/navbar";

export const metadata: Metadata = {
  title: "BonVoyage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  isLayoutNotApplied,
}: Readonly<{
  children: React.ReactNode;
  isLayoutNotApplied?: boolean;
}>) {
  return (
    <html>
      <body>
        <ToastContainer position="top-center" />
        <StoreProvider>
          <div className="layout">
            <div className="layout__header">{/* <Header /> */}</div>
            <div className="layout__body">{children}</div>
            <div className="layout__footer">{/* <Footer /> */}</div>
          </div>
        </StoreProvider>
        {!isLayoutNotApplied && <Navbar />}
      </body>
    </html>
  );
}
