import { query, check , body } from 'express-validator';

const update = [
    body("name")
      .optional()
      .bail()
      .notEmpty()
      .withMessage("Name cannot be empty")
      .bail()
      .isString()
      .withMessage("Name must be a string")
      .isLength({ max: 30 })
      .withMessage("Name cannot be more than 30 characters"),
    body("address")
      .optional()
      .bail()
      .notEmpty()
      .withMessage("Address cannot be empty")
      .bail()
      .isString()
      .withMessage("Address must be a string")
      .isLength({ max: 30 })
      .withMessage("Address cannot be more than 30 characters"),
    body("role")
      .optional()
      .bail()
      .notEmpty()
      .withMessage("Role cannot be empty")
      .bail()
      .isString()
      .withMessage("Role must be a string")
      .bail()
      .isIn(["USER", "SUPER_ADMIN"])
      .withMessage("Role must be one of 'USER' or 'SUPER_ADMIN'"),
  ];
const updateProfile = [
    body("name")
        .optional()
        .bail()
        .notEmpty()
        .withMessage("Name cannot be empty")
        .bail()
        .isString()
        .withMessage("Name must be a string")
        .isLength({ max: 30 })
        .withMessage("Name cannot be more than 30 characters"),
    body("address")
        .optional()
        .bail()
        .notEmpty()
        .withMessage("Address cannot be empty")
        .bail()
        .isString()
        .withMessage("Address must be a string")
        .isLength({ max: 30 })
        .withMessage("Address cannot be more than 30 characters"),
    body("phoneNo")
        .optional()
        .bail()
        .notEmpty()
        .withMessage("phoneNo cannot be empty")
        .bail()
        .isNumeric()
        .withMessage("phoneNo must be a number")
        .bail()
        .isLength({ max: 30 })
        .withMessage("phoneNo cannot be more than 30 characters"),
    body("profilePic")
        .optional()
        .bail()
        .notEmpty()
        .withMessage("profilePic cannot be empty")
        .bail()
        .isString()
        .withMessage("profilePic must be a string")
        .isLength({ max: 100 })
        .withMessage("Image file name cannot be more than 100 characters"),
    body("gender")
        .optional()
        .bail()
        .notEmpty()
        .withMessage("Gender cannot be empty")
        .bail()
        .isString()
        .withMessage("Gender must be a string")
        .isIn(["male", "female", "other"])
        .withMessage("Gender must be one of 'male', 'female', or 'other'")
];


export { update, updateProfile };